version: "1.0"

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  poet:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    depends_on:
      - mariadb
    ports:
      - "${HOST_PORT}:8000"
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOSTNAME=mariadb # This is the service name of the mariadb container.
      - DATABASE_PORT=${DATABASE_PORT}

volumes:
  mariadb_data:
