"""Initial

Revision ID: a6270a45c3af
Revises: 03b3f42a5b00
Create Date: 2024-02-25 22:27:48.571762

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6270a45c3af'
down_revision: Union[str, None] = '03b3f42a5b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basemarker', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'basemarker', 'template', ['template_id'], ['id'])
    op.add_column('compositemaker', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'compositemaker', 'template', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'compositemaker', type_='foreignkey')
    op.drop_column('compositemaker', 'template_id')
    op.drop_constraint(None, 'basemarker', type_='foreignkey')
    op.drop_column('basemarker', 'template_id')
    # ### end Alembic commands ###
