"""Initial

Revision ID: b29926c6dfa2
Revises: 
Create Date: 2024-02-25 22:23:18.590669

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29926c6dfa2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basemarker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basemarker_description'), 'basemarker', ['description'], unique=False)
    op.create_index(op.f('ix_basemarker_id'), 'basemarker', ['id'], unique=False)
    op.create_index(op.f('ix_basemarker_name'), 'basemarker', ['name'], unique=False)
    op.create_table('compositemaker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('composite_options', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compositemaker_id'), 'compositemaker', ['id'], unique=False)
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_description'), 'template', ['description'], unique=False)
    op.create_index(op.f('ix_template_id'), 'template', ['id'], unique=False)
    op.create_index(op.f('ix_template_name'), 'template', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_name'), table_name='template')
    op.drop_index(op.f('ix_template_id'), table_name='template')
    op.drop_index(op.f('ix_template_description'), table_name='template')
    op.drop_table('template')
    op.drop_index(op.f('ix_compositemaker_id'), table_name='compositemaker')
    op.drop_table('compositemaker')
    op.drop_index(op.f('ix_basemarker_name'), table_name='basemarker')
    op.drop_index(op.f('ix_basemarker_id'), table_name='basemarker')
    op.drop_index(op.f('ix_basemarker_description'), table_name='basemarker')
    op.drop_table('basemarker')
    # ### end Alembic commands ###
