"""Initial

Revision ID: c34b987924c7
Revises: a6270a45c3af
Create Date: 2024-02-25 22:53:14.687807

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c34b987924c7'
down_revision: Union[str, None] = 'a6270a45c3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compositemarker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('composite_options', sa.JSON(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compositemarker_id'), 'compositemarker', ['id'], unique=False)
    op.drop_index('ix_compositemaker_id', table_name='compositemaker')
    op.drop_table('compositemaker')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compositemaker',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('composite_options', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('template_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], name='compositemaker_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_index('ix_compositemaker_id', 'compositemaker', ['id'], unique=False)
    op.drop_index(op.f('ix_compositemarker_id'), table_name='compositemarker')
    op.drop_table('compositemarker')
    # ### end Alembic commands ###
